config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  #logout
  delete '/logout' => 'sessions#destroy'

  resources :items do 
    resources :bids
  end

  resources :categories
  resources :bids
  
  resources :users do 
    resources :items, shallow: true
  end 


  #root 'sessions#omniauth'

  #get '/auth/google_oath2/callback', to: 'sessions#omniauth' #static for google
  get '/auth/:provider/callback', to: 'sessions#google' #dynamic for whatever provider sign in


end

app/models/bid.rb
class Bid < ApplicationRecord
    belongs_to :user
    belongs_to :item

    validates :price, presence: true, numericality: { only_integer: true }

    #scope :alpha, -> { order(:bid) }
    scope :highest_bidder, -> {order(:price).reverse_order}
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
    before_action :redirect_if_not_logged_in
    
    def index
        if params[:item_id] && @item = Item.find_by_id(:item_id)
            @bids = @item.bids.highest_bidder
        else
            @error = "That item does not exist. Please try again." if params[:item_id]
            @bids = Bid.highest_bidder

        end
    end

    def new
        #if nested and we find the item
        if params[:item_id] && @item = Item.find_by_id(params[:item_id])
            @bid = @item.bids.build
        else
            #@error = "That item does not exist. Default item is selected."
            @bid = Bid.new
        end
    end
    
    def create
        @bid = current_user.bids.build(bid_params)
        if @bid.save
            redirect_to bids_path
        else
            render :new 
        end
    end

    def show
        @bid = Bid.find_by(id: params[:id])
    end

    private 

    def bid_params
        params.require(:bid).permit(:price, :item_id)
    end
    
end

app/helpers/bids_helper.rb
module BidsHelper

    def display_item_fields(i)
        if params[:item_id]
            i.hidden_field :item_id
        else
            render partial: 'item_select'
            
            #, locals: {f: i}
        end
    end

    def display_header(item)
        if item
            tag.h1("Current for #{item.title}")
        else
            tag.h1("Current Bids")
        end
    end
end

app/views/bids/index.html.erb
<% if @item %>
  <h1>Bids for <%= @item.title%></h1>
<% else %>
  <h1>Highest Bidders</h1>
<% end %>

<ul>
<% @bids.each do |c|%>
  <li><%= c.user.username%> bidded $<%= c.price%> on <strong><%= link_to c.item.title, item_path(c.item_id) %></strong></li>
<% end %>
</ul>

app/views/bids/new.html.erb
<% if @bid.item %>
    <h1>Bid for <%= @bid.item.title %>! </h1>
<% else %>
    <h1>Bid on an item</h1>
    <p>*Bids cannot be changed after submitting! Please confirm item and amount before bidding.*</p>
<% end %>
<br>

<%= render partial: "layouts/errors", locals: {object: @bid} %>


<%= form_for([@bid.item, @bid]) do |f| %>

    <% if !@bid.item %>
        <%= f.label :item %>
        <%= f.collection_select :item_id, Item.all, :id, :title%>
    <% else %>
        <%= f.hidden_field :item_id %>
    <% end %>

    <%= f.label :price %>
    $<%= f.text_field :price %>

    <%= f.submit "Submit Bid" %>

<% end %>

app/views/bids/show.html.erb
<h3><%= @bid.user.username %> bidded $<%= @bid.price %></h3>

<h4>Bid is for this Item: <%= link_to @bid.item.title, item_path(@bid.item_id) %> </h4>