config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  #logout
  delete '/logout' => 'sessions#destroy'

  resources :items do 
    resources :bids
  end

  resources :categories
  resources :bids
  
  resources :users do 
    resources :items, shallow: true
  end 


  #root 'sessions#omniauth'

  #get '/auth/google_oath2/callback', to: 'sessions#omniauth' #static for google
  get '/auth/:provider/callback', to: 'sessions#google' #dynamic for whatever provider sign in


end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :categories
  has_many :bids, dependent: :destroy
  has_many :users, through: :bids


  validates :description, :title, presence: true
  validate :over_daily_limit

  scope :alpha, -> { order(:title) }

  def over_daily_limit
    today_items = user.items.select do |i|
      i.created_at.try(:to_date) == Date.today
    end

    if today_items.size > 2
      errors.add(:item_id, "can't post due to already posting over 3 items today.")
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_item, only: [:edit, :update, :show, :destroy]
    
    def index
        if params[:user_id] && @user = User.find_by_id(params[:user_id])
            @items = @user.items.alpha
        else
            @error = "That item does not exist. Please try again." if params[:user_id]
            @items = Item.alpha
        end
    end
    
    def destroy
        @item.destroy
        redirect_to items_path
    end

    def new
        @item = Item.new
    end
    
    def create
        @item = current_user.items.build(item_params)
        if @item.save
            redirect_to items_path
        else
            render :new 
        end
    end

    def edit
        redirect_to items_path if !@item || @item.user != current_user
    end

    def update
        redirect_to items_path if !@item || @item.user != current_user
       if @item.update(item_params)
         redirect_to item_path(@item)
       else
         render :edit
       end
     end

    def show
    end

    private 

    def item_params
        params.require(:item).permit(:title, :description)
    end
    
    def set_item
        @item = Item.find_by_id(params[:id])
    end

end

app/helpers/items_helper.rb
module ItemsHelper
  def index_display_header
    if @user
      content_tag(:h2, "#{@user.username}'s Posted Items:")
    else
      content_tag(:h2, "All Items")
    end
  end

end

app/views/items/_items.html.erb
<ul>
    <% items.each do |i|%>
      <li><%= link_to i.title, item_path(i) %> - <%= i.description %></li>
    <% end %>
</ul>

app/views/items/edit.html.erb
<h1>Edit <%= @item.title%>!</h1>

<%= render partial: "layouts/errors", locals: {object: @item} %>

<%= form_for(@item) do |f|%>

  <br>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>


  <%= f.submit %>

<% end %>

app/views/items/index.html.erb
<%= index_display_header %>

<% if @items.blank? %>
    <h3>No posted items yet. Post an item <%= link_to "here", new_item_path%></h3>
<% else %>
    <%= render partial: "items", locals: {items: @items} %>
<% end %>

app/views/items/new.html.erb
<h1>Post an Item</h1>

<%= render partial: "layouts/errors", locals: {object: @item} %>


<%= form_for(@item) do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.submit "Post Item" %>

<% end %>

app/views/items/show.html.erb
<h1>Item for Sale: <%= @item.title %></h1>
<div>Description: <%= @item.description %></div>
<h4>Posted by: <%= @item.user.username %></h4>
<br>

<% if @item.user == current_user %>
<h4><%= link_to "Edit", edit_item_path(@item)%></h4>
<h4><%= link_to 'Delete', item_path(@item), method: 'delete', data: { confirm: 'Are you sure you want to remove this item?'}%></h4>
<% end %>

<h4><%= link_to 'See Highest Bidders', item_bids_path(@item) %></h4>
<h4><%= link_to 'Add a new bid', new_item_bid_path(@item) %> </h4>
<br>

<h3>Bids Timeline</h3>
<% if !@item.bids.blank? %>
    <% @item.bids.each do |c| %>
        <li><strong><%= c.user.username %></strong> bidded: "<%= link_to c.price, item_bid_path(@item, c)%>" </li>
    <% end %>
<% else %>
    <h4>No bids at the moment</h4>
<% end %>