config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  #logout
  delete '/logout' => 'sessions#destroy'

  resources :items do 
    resources :bids
  end

  resources :categories
  resources :bids
  
  resources :users do 
    resources :items, shallow: true
  end 


  #root 'sessions#omniauth'

  #get '/auth/google_oath2/callback', to: 'sessions#omniauth' #static for google
  get '/auth/:provider/callback', to: 'sessions#google' #dynamic for whatever provider sign in


end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link ref="stylesheets" href="/bootstrap.min.css">
    <link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>BidWars</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <div>
      <br>
      <% if logged_in? %>

          <%= link_to "Home", user_path(current_user) %> |
          <%= link_to 'Post an Item', new_item_path %> | 
          <%= link_to 'Browse Items', items_path %> | 
          <%= link_to 'Bid on an Item', new_bid_path %> | 
          <%= link_to "My Posts", user_items_path(current_user) %> |
          <%= link_to 'Logout', logout_path, method:'delete' %>

      <% else %>
      <%= link_to 'Sign Up for BidWars Account', signup_path %> |
      <%= link_to 'Log In', login_path %> |
      <%= link_to "Log In With Google", '/auth/google_oauth2', method: :post%>
      

      <% end %>
    </div>
    <br>
    <div>
      <% if flash[:message] %>
        <%= flash[:message]%>

      <% end %>
      <%= @error %>
    </div>
      <%= yield %>
  </body>
</html>